### ISSUE TITLE
Where are the tasks described?

### ISSUE THREAD

**Issue by ebrahim78652** [Jarcionek/java-8-exercises#4]

**Comment by Jarcionek** [comment]
Look for the methods with `exercise_` prefix. The tasks are explained in the comment just below the method declaration.

See [example](https://github.com/Jarcionek/java-8-exercises/blob/master/src/main/java/uk/co/jpawlak/java8exercises/exercises/Pack_1_LambdasAndMethodReferences.java#L181).

**Comment by ebrahim78652** [comment]
Thank you for the reply.
